ATTEMPTS TO DISPLAY DECADE AND SEND CORRECTNESS
I tried alerting with a return string, just like I did in createtable, (function displaydecade), but that didn't work. I even tried making the method just GET, and that didn't help either!!!

I mean... this is a problem in Python, right? Um... well, it says the data error happened at 'at http://localhost:3000/static/js/bundle.js:118:34', so idk. Sounds pretty jsey to me. But that's probably because the js is administrating the variables, right???

omg, so it looks like I forgot to change the var url in my check function (it was still '/nextphoto'!) That could be a problem!!! Nop, fixing that didn't seem to help... is there more of this stuff that I need to change when it's GET and POST? Other than the method in the config? Uh... let me go look at the POST functions from class...

(I tried putting in a displaydecade button, because I forgot to do that before, but it's just not working)

Now, I feel like I don't entirely get how in the example it's like
    login() {...
axios(config).then((resp) => {this.setState({...this.state,
                usercount: resp.data['user count'],
                totalcount: resp.data['total count'] ... }'
Like, what's the deal with 'user count' and 'total count'? Those aren't variables!!! I mean, it looks like those are JSON labels...

Hey!!! My little correct checker at the bottom of check suddenly turned gray! While I was there, I made sure that decade and userdecade were the same type. Oh I see, it was gray because I had an early return.

Grrr!!! Same problem!!! Let me paste it again here...
'Cannot read properties of undefined (reading 'data')
TypeError: Cannot read properties of undefined (reading 'data')
    at http://localhost:3000/static/js/bundle.js:117:34'

So, the data is the thing I'm trying to bring from the Python to the js? Right? Well, I initialized my correct variable, didn't I??? Haha, oh wait, no I didn't...

Well, that would have been embarrassing if that was the whole problem, that I forgot to initialize correct, but I'm still getting the same error!!!

So, is there a problem with me returning two different jsonifys for two different routes? I mean, it seems like it would just add on, since I've already got unjsonified variables anyway. Well, what's wrong with my data???

OK, I'm googling this again. Here, I see some people talking about async/await. Do those have to do with avoiding undefined messes??? Seems complicated.

Here's someone using 'axios.post'. I'm going to try that!!! I have no idea what I'm doing. This would have been in the homework somewhere, right??? I'm just going to comment all of THAT out for now...