STARTING WEB IMG HOSTING
As a temporary solution, I'm going to use an image hosting site. Imgbb, I guess? I mean that doesn't seem very stable, but...

omg, well great, I added urls to the database but not the createtable button isn't returning anything!!! aaaa, i will try to get this working later.

Luckily, there's an error message in Python. Apparently '    (line0, line1, line2, line3, line4, line5) = linelist
^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 5)' I thought I changed everything I needed to, but apparently not!!!